services:
  front:
    container_name: sistersmade-front
    build:
      context: ../sistersmade-front
      dockerfile: ./Dockerfile-front
    ports:
      - "4200:4200"
    volumes:
      - ../sistersmade-front:/app:delegated
      - ../sistersmade-front/node_modules:/app/node_modules:delegated
    networks:
      - sistersmade

  back:
    container_name: sistersmade-back
    build:
      context: ../sistersmade-back
      dockerfile: ./Dockerfile-back
    ports:
      - "8080:8080"
    networks:
      - sistersmade

networks:
  sistersmade:
